// Generated by Cypress Author — 2026-05-22
// Load .env and .env.local before anything else — Cypress tasks run outside
// Next.js so environment variables aren't populated automatically.
import "dotenv/config";
import { config as dotenvLocalConfig } from "dotenv";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
if (existsSync(resolve(__dirname, ".env.local"))) {
  dotenvLocalConfig({ path: resolve(__dirname, ".env.local"), override: true });
}

import { PrismaPg } from "@prisma/adapter-pg";
import { defineConfig } from "cypress";
import { randomBytes, scrypt } from "node:crypto";

// Replicates @better-auth/utils/password scrypt params so seeded passwords
// are accepted by the Better Auth sign-in endpoint.
function deriveKey(password: string, salt: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(
      password.normalize("NFKC"),
      salt,
      64,
      { N: 16384, r: 16, p: 1, maxmem: 128 * 16384 * 16 * 2 },
      (err, key) => {
        if (err) reject(err);
        else resolve(key);
      },
    );
  });
}

async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16).toString("hex");
  const key = await deriveKey(password, salt);
  return `${salt}:${key.toString("hex")}`;
}

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3000",
    specPattern: "cypress/e2e/**/*.cy.ts",
    supportFile: "cypress/support/e2e.ts",
    screenshotsFolder: "cypress/screenshots",
    videosFolder: "cypress/videos",
    setupNodeEvents(on) {
      on("task", {
        async seedTestUser({
          email,
          password,
          name,
        }: {
          email: string;
          password: string;
          name: string;
        }) {
          const { PrismaClient } =
            await import("./src/generated/prisma/client");
          const adapter = new PrismaPg({
            connectionString: process.env.DATABASE_URL!,
          });
          const prisma = new PrismaClient({ adapter });
          try {
            const hash = await hashPassword(password);
            const now = new Date();

            const user = await prisma.user.upsert({
              where: { email },
              create: {
                id: crypto.randomUUID(),
                email,
                name,
                emailVerified: true,
                createdAt: now,
                updatedAt: now,
              },
              update: { emailVerified: true, updatedAt: now },
            });

            const existingAccount = await prisma.account.findFirst({
              where: { userId: user.id, providerId: "credential" },
            });

            if (existingAccount) {
              await prisma.account.update({
                where: { id: existingAccount.id },
                data: { password: hash, updatedAt: now },
              });
            } else {
              await prisma.account.create({
                data: {
                  id: crypto.randomUUID(),
                  accountId: user.id,
                  providerId: "credential",
                  userId: user.id,
                  password: hash,
                  createdAt: now,
                  updatedAt: now,
                },
              });
            }

            return user.id;
          } finally {
            await prisma.$disconnect();
          }
        },

        async seedTestLink({
          email,
          url,
          title,
        }: {
          email: string;
          url: string;
          title?: string;
        }) {
          const { PrismaClient } =
            await import("./src/generated/prisma/client");
          const adapter = new PrismaPg({
            connectionString: process.env.DATABASE_URL!,
          });
          const prisma = new PrismaClient({ adapter });
          try {
            const user = await prisma.user.findUniqueOrThrow({
              where: { email },
            });
            const domain = new URL(url).hostname;
            const link = await prisma.link.create({
              data: {
                url,
                title: title ?? domain,
                favicon: `https://${domain}/favicon.ico`,
                domain,
                userId: user.id,
                ingestStatus: "SKIPPED",
              },
            });
            return link.id;
          } finally {
            await prisma.$disconnect();
          }
        },

        async cleanupTestLinks({ email }: { email: string }) {
          const { PrismaClient } =
            await import("./src/generated/prisma/client");
          const adapter = new PrismaPg({
            connectionString: process.env.DATABASE_URL!,
          });
          const prisma = new PrismaClient({ adapter });
          try {
            const user = await prisma.user.findUnique({ where: { email } });
            if (user) {
              await prisma.linkContent.deleteMany({
                where: { link: { userId: user.id } },
              });
              await prisma.link.deleteMany({ where: { userId: user.id } });
            }
          } finally {
            await prisma.$disconnect();
          }
          return null;
        },

        async cleanupTestUser({ email }: { email: string }) {
          const { PrismaClient } =
            await import("./src/generated/prisma/client");
          const adapter = new PrismaPg({
            connectionString: process.env.DATABASE_URL!,
          });
          const prisma = new PrismaClient({ adapter });
          try {
            const user = await prisma.user.findUnique({ where: { email } });
            if (user) {
              // Delete in FK-safe order
              await prisma.linkContent.deleteMany({
                where: { link: { userId: user.id } },
              });
              await prisma.link.deleteMany({ where: { userId: user.id } });
              await prisma.session.deleteMany({ where: { userId: user.id } });
              await prisma.account.deleteMany({ where: { userId: user.id } });
              await prisma.user.delete({ where: { email } });
            }
          } finally {
            await prisma.$disconnect();
          }
          return null;
        },
      });
    },
  },
});
