packages: []

overrides:
  ip-address: 10.1.1
  jsdom: 25.0.1

allowBuilds:
  '@prisma/engines': true
  cypress: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
