// Generated by Cypress Author — 2026-05-22

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Log in programmatically via the Better Auth sign-in endpoint.
       * Uses cy.session() to cache cookies so the login only runs once per spec.
       */
      loginByApi(email: string, password: string): Chainable<void>;
    }
  }
}

Cypress.Commands.add("loginByApi", (email: string, password: string) => {
  cy.session(
    [email, password],
    () => {
      cy.request({
        method: "POST",
        url: "/api/auth/sign-in/email",
        body: { email, password },
        failOnStatusCode: true,
      })
        .its("status")
        .should("eq", 200);
    },
    {
      // Validate the cached session is still alive before reusing it
      validate() {
        cy.request({ url: "/home", failOnStatusCode: false })
          .its("status")
          .should("not.eq", 302);
      },
    },
  );
});

export {};
