// Generated by Cypress Author — 2026-05-22
import "./commands";

// Next.js App Router triggers React hydration mismatches in the Cypress browser
// environment (locale-dependent date formatting, SSR/client divergence). These
// are non-fatal in testing — suppress them so they don't abort otherwise-passing tests.
Cypress.on("uncaught:exception", (err) => {
  if (err.message.includes("Hydration failed")) return false;
  if (err.message.includes("hydration")) return false;
  return true;
});
