// Generated by Cypress Author — 2026-05-22

describe("Authentication", () => {
  const email = Cypress.env("TEST_USER_EMAIL") as string;
  const password = Cypress.env("TEST_USER_PASSWORD") as string;
  const name = Cypress.env("TEST_USER_NAME") as string;
  // Unique email per run so sign-up doesn't collide with the shared test user.
  const signupEmail = `cypress-signup-${Date.now()}@example.com`;

  before(() => {
    cy.task("seedTestUser", { email, password, name });
  });

  after(() => {
    cy.task("cleanupTestUser", { email });
    cy.task("cleanupTestUser", { email: signupEmail });
  });

  describe("Sign in", () => {
    beforeEach(() => {
      cy.clearCookies();
      cy.visit("/login");
    });

    it("valid credentials → redirected to /home", () => {
      cy.get('[data-cy="email-input"]').type(email);
      cy.get('[data-cy="password-input"]').type(password);
      cy.get('[data-cy="sign-in-button"]').click();
      cy.url().should("include", "/home");
    });

    it("wrong password → error toast shown", () => {
      cy.get('[data-cy="email-input"]').type(email);
      cy.get('[data-cy="password-input"]').type("wrong-password-xyz");
      cy.get('[data-cy="sign-in-button"]').click();
      cy.get('[data-sonner-toast]').should("be.visible");
    });

    it("empty fields → inline validation errors shown", () => {
      cy.get('[data-cy="sign-in-button"]').click();
      cy.get('[role="alert"]').should("have.length.gte", 1);
    });
  });

  describe("Sign up", () => {
    it("valid details → redirected to /verify-email", () => {
      cy.clearCookies();
      cy.visit("/signup");
      cy.get('[data-cy="name-input"]').type("Cypress Signup");
      cy.get('[data-cy="email-input"]').type(signupEmail);
      cy.get('[data-cy="password-input"]').type("TestPass123!");
      cy.get('[data-cy="confirm-password-input"]').type("TestPass123!");
      cy.get('[data-cy="sign-up-button"]').click();
      cy.url().should("include", "/verify-email");
    });
  });

  describe("Sign out", () => {
    beforeEach(() => {
      cy.loginByApi(email, password);
      cy.visit("/home");
    });

    it("sign out → redirected to /login", () => {
      cy.get('[data-cy="user-menu-button"]').click();
      cy.get('[data-cy="sign-out-menu-item"]').click();
      cy.url().should("include", "/login");
    });
  });

  describe("Already authenticated", () => {
    it("visiting /login → redirected to /home", () => {
      cy.loginByApi(email, password);
      cy.visit("/login");
      cy.url().should("include", "/home");
    });
  });
});
