// Generated by Cypress Author — 2026-05-22

const TEST_URL_A = "https://nublson.com";
const TEST_URL_B = "https://github.com";

describe("Link management", () => {
  const email = Cypress.env("TEST_USER_EMAIL") as string;
  const password = Cypress.env("TEST_USER_PASSWORD") as string;
  const name = Cypress.env("TEST_USER_NAME") as string;

  before(() => {
    cy.task("seedTestUser", { email, password, name });
  });

  after(() => {
    cy.task("cleanupTestUser", { email });
  });

  beforeEach(() => {
    cy.task("cleanupTestLinks", { email });
    cy.loginByApi(email, password);
  });

  it("new user with no links sees the empty state", () => {
    cy.visit("/home");
    cy.get('[data-cy="link-group-empty"]').should("exist");
    cy.contains("No Links Yet").should("be.visible");
  });

  it("seeded link renders title and domain", () => {
    cy.task("seedTestLink", { email, url: TEST_URL_A, title: "Nubelson Fernandes" });
    cy.visit("/home");
    cy.get('[data-cy="link-item"]').should("have.length", 1);
    cy.get('[data-cy="link-title"]').should("contain.text", "Nubelson Fernandes");
    cy.get('[data-cy="link-domain"]').should("contain.text", "nublson.com");
  });

  it("delete a link → removed from the list", () => {
    cy.task("seedTestLink", { email, url: TEST_URL_A });
    cy.visit("/home");
    cy.get('[data-cy="link-item"]').should("have.length", 1);

    // The menu button is opacity-0 until hover on pointer devices;
    // force:true bypasses Cypress visibility check without affecting delete logic.
    cy.get('[aria-label="Open link menu"]').click({ force: true });
    cy.get('[data-cy="delete-link-menu-item"]').click();

    cy.get('[data-cy="link-item"]').should("not.exist");
    cy.get('[data-cy="link-group-empty"]').should("exist");
  });

  it("search dialog filters links by title", () => {
    cy.task("seedTestLink", { email, url: TEST_URL_A, title: "Nubelson Fernandes" });
    cy.task("seedTestLink", { email, url: TEST_URL_B, title: "GitHub" });

    cy.visit("/home");
    cy.get('[data-cy="link-item"]', { timeout: 10000 }).should("have.length", 2);

    cy.get('[aria-label="Search links"]').click();
    // cmdk library adds the [cmdk-input] attribute to the actual <input> element.
    // Scope link-item assertions within the dialog — the main page list is still
    // in the DOM and would otherwise inflate the count.
    cy.get('[cmdk-input]').type("GitHub");
    cy.get('[role="dialog"]').find('[data-cy="link-item"]').should("have.length", 1);
    cy.get('[role="dialog"]').find('[data-cy="link-title"]').should("contain.text", "GitHub");

    cy.get('[cmdk-input]').clear().type("xyz-nonexistent-query");
    cy.contains("No results found.").should("be.visible");
  });
});
