// Generated by Cypress Author — 2026-05-22

const TEST_URL = "https://nublson.com";
const INVALID_URL = "not-a-url";

describe("Link saving — core journey", () => {
  const email = Cypress.env("TEST_USER_EMAIL") as string;
  const password = Cypress.env("TEST_USER_PASSWORD") as string;
  const name = Cypress.env("TEST_USER_NAME") as string;

  before(() => {
    cy.task("seedTestUser", { email, password, name });
  });

  after(() => {
    cy.task("cleanupTestUser", { email });
  });

  beforeEach(() => {
    // Remove all links before each test to ensure a clean, isolated state.
    cy.task("cleanupTestLinks", { email });
    cy.loginByApi(email, password);
  });

  it("seed a link → renders in the list on /home", () => {
    // Insert a Link row directly via Prisma — no outbound HTTP, no ingest pipeline.
    cy.task("seedTestLink", { email, url: TEST_URL });

    cy.visit("/home");
    cy.get('[data-cy="link-item"]', { timeout: 10000 }).should("exist");
  });

  it("submit invalid URL via API → 400 with error message", () => {
    // The route validates the URL before any outbound fetch, so no pipeline risk.
    cy.request({
      method: "POST",
      url: "/api/links",
      body: { url: INVALID_URL },
      headers: { "Content-Type": "application/json" },
      failOnStatusCode: false,
    }).then((response) => {
      expect(response.status).to.eq(400);
      expect(response.body).to.have.property("error");
    });
  });

  it("saved link → persists across page visits", () => {
    cy.task("seedTestLink", { email, url: TEST_URL });

    cy.visit("/home");
    cy.get('[data-cy="link-item"]', { timeout: 10000 }).should("exist");

    // Re-visit to confirm the link is stored persistently, not just in memory.
    cy.visit("/home");
    cy.get('[data-cy="link-item"]', { timeout: 10000 }).should("exist");
  });

  it("unauthenticated visitor → redirected to /login when accessing /home", () => {
    cy.clearCookies();
    cy.visit("/home", { failOnStatusCode: false });
    cy.url().should("include", "/login");
  });
});
